// <auto-generated />
using System;
using ApplicantPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicantPortal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240413204757_“languageMigration")]
    partial class languageMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicantModelProgrammeModel", b =>
                {
                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<int>("ProgrammesId")
                        .HasColumnType("integer");

                    b.HasKey("ApplicantId", "ProgrammesId");

                    b.HasIndex("ProgrammesId");

                    b.ToTable("ApplicantModelProgrammeModel");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.AcademicExperienceModel", b =>
                {
                    b.Property<string>("InstitutionName")
                        .HasColumnType("text");

                    b.Property<int>("ApplicantModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Certificate")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionAddress")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("ProgrammeStudied")
                        .HasColumnType("text");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("InstitutionName");

                    b.HasIndex("ApplicantModelId");

                    b.ToTable("AcademicExperienceModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.AddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<string>("Box")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Gprs")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("AddressModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ApplicantIssueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Issue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("ApplicantIssueModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ApplicantModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionType")
                        .HasColumnType("text")
                        .HasColumnName("AdmissionType");

                    b.Property<bool?>("Admitted")
                        .HasColumnType("boolean");

                    b.Property<int?>("AdmittedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AltPhone")
                        .HasColumnType("text")
                        .HasColumnName("AltPhone");

                    b.Property<long>("ApplicationNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("ApplicationNumber");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<bool?>("Awaiting")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateAdmitted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Denomination")
                        .HasColumnType("text");

                    b.Property<bool?>("Disability")
                        .HasColumnType("boolean");

                    b.Property<int?>("DisabilityType")
                        .HasColumnType("integer");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<bool?>("Eligible")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EmergencyContact");

                    b.Property<string>("EntryMode")
                        .HasColumnType("text")
                        .HasColumnName("EntryMode");

                    b.Property<string>("ExternalHostel")
                        .HasColumnType("text");

                    b.Property<bool?>("FeePaying")
                        .HasColumnType("boolean");

                    b.Property<int?>("FirstChoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstQualification")
                        .HasColumnType("text")
                        .HasColumnName("FirstQualification");

                    b.Property<string>("FormerSchool")
                        .HasColumnType("text");

                    b.Property<int?>("FormerSchoolNewId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Gender");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("GuardianName")
                        .HasColumnType("text");

                    b.Property<string>("GuardianOccupation")
                        .HasColumnType("text");

                    b.Property<string>("GuardianPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("GuardianPhone");

                    b.Property<string>("GuardianRelationship")
                        .HasColumnType("text");

                    b.Property<int?>("HallAdmitted")
                        .HasColumnType("integer");

                    b.Property<int?>("HallId")
                        .HasColumnType("integer");

                    b.Property<string>("Hometown")
                        .HasColumnType("text");

                    b.Property<string>("IndexNo")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int?>("LastYearInSchool")
                        .HasColumnType("integer");

                    b.Property<bool?>("LetterPrinted")
                        .HasColumnType("boolean");

                    b.Property<string>("LevelAdmitted")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text")
                        .HasColumnName("MaritalStatus");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("integer");

                    b.Property<int?>("NoOfChildren")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<string>("PostGprs")
                        .HasColumnType("text");

                    b.Property<string>("PreferredHall")
                        .HasColumnType("text");

                    b.Property<string>("PreviousIndexNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ProgrammeAdmittedId")
                        .HasColumnType("integer");

                    b.Property<string>("ProgrammeStudied")
                        .HasColumnType("text");

                    b.Property<bool?>("ReceivedSms")
                        .HasColumnType("boolean");

                    b.Property<string>("Referrals")
                        .HasColumnType("text");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Reported")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ReportedInSchool")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ResidentialStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("Results")
                        .HasColumnType("text");

                    b.Property<string>("RoomNo")
                        .HasColumnType("text");

                    b.Property<int?>("SecondChoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("SecondQualification")
                        .HasColumnType("text")
                        .HasColumnName("SecondQualification");

                    b.Property<string>("SectionAdmitted")
                        .HasColumnType("text");

                    b.Property<string>("SourceOfFinance")
                        .HasColumnType("text");

                    b.Property<bool?>("SponsorShip")
                        .HasColumnType("boolean");

                    b.Property<string>("SponsorShipCompany")
                        .HasColumnType("text");

                    b.Property<string>("SponsorShipCompanyContact")
                        .HasColumnType("text");

                    b.Property<string>("SponsorShipLocation")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Applicant")
                        .HasColumnName("Status");

                    b.Property<int?>("ThirdChoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.Property<string>("YearOfAdmission")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FormerSchoolNewId");

                    b.HasIndex("HallId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("RegionId");

                    b.HasIndex("ReligionId");

                    b.ToTable("ApplicantModel", (string)null);
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.BankModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BankModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.Choices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstChoiceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondChoiceId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThirdChoiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("FirstChoiceId");

                    b.HasIndex("SecondChoiceId");

                    b.HasIndex("ThirdChoiceId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ConfigurationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionsOfficer")
                        .HasColumnType("text");

                    b.Property<DateTime>("FeesDeadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Matriculation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("MedicalEnds")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("MedicalStarts")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OrientationEnds")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OrientationStarts")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Reporting")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.CountryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CountryModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DenominationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DenominationModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("DepartmentModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DisabilitiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DisabilitiesModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DistrictModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DistrictModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DocumentUploadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("DocumentUploadModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ExamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CutOffPoint")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExamModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.FacultyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacultyModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.FormNoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("No")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormNoModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.FormerSchoolModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FormerSchoolModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.GradeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("Exam")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GradeModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.HallModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankAccount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HallModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.LanguageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantModelID")
                        .HasColumnType("integer");

                    b.Property<int?>("Name")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ProgrammeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("LevelAdmitted")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Running")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowOnPortal")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ProgrammeModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ProgressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AcademicExperience")
                        .HasColumnType("boolean");

                    b.Property<bool>("Age")
                        .HasColumnType("boolean");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<bool?>("Biodata")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool?>("DocumentUpload")
                        .HasColumnType("boolean");

                    b.Property<bool>("FormCompletion")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Picture")
                        .HasColumnType("boolean");

                    b.Property<bool>("Qualification")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Referee")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ResearchInformation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ResearchPublication")
                        .HasColumnType("boolean");

                    b.Property<bool>("Results")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WorkingExperience")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ProgressModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.RefereeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantModelId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("RefereeStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantModelId");

                    b.ToTable("RefereeModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.RegionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RegionModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ReligionModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReligionModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.RequirementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<int>("Department")
                        .HasColumnType("integer");

                    b.Property<string>("RuleOne")
                        .HasColumnType("text");

                    b.Property<string>("RuleThree")
                        .HasColumnType("text");

                    b.Property<string>("RuleTwo")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequirementModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ResearchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualAreaOfResearch")
                        .HasColumnType("text");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<string>("AreaOfResearchIfAdmitted")
                        .HasColumnType("text");

                    b.Property<string>("FutureResearchInterest")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("ResearchModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ResearchPublicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<string>("Publication")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("ResearchPublicationModel");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ResultUploadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Center")
                        .HasColumnType("text");

                    b.Property<string>("ExamType")
                        .HasColumnType("text");

                    b.Property<int>("Form")
                        .HasColumnType("integer");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int?>("GradeOld")
                        .HasColumnType("integer");

                    b.Property<string>("GradeValueOld")
                        .HasColumnType("text");

                    b.Property<string>("IndexNo")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<string>("OldSubject")
                        .HasColumnType("text");

                    b.Property<string>("Sitting")
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantModelId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ResultUploadModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SHSAttendedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<bool>("AttendedTTU")
                        .HasColumnType("boolean");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("NameId")
                        .HasColumnType("integer");

                    b.Property<string>("ProgrammeStudied")
                        .HasColumnType("text");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("LocationId");

                    b.HasIndex("NameId");

                    b.ToTable("ShsAttendedModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SHSProgrammes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShsProgrammes");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SchoolModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("SchoolModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SmsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Applicant")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<long>("Recipient")
                        .HasColumnType("bigint");

                    b.Property<string>("SentBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmsModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SubjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubjectModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Reminder")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.UniversityAttendedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CGPA")
                        .HasColumnType("numeric");

                    b.Property<string>("DegreeClassification")
                        .HasColumnType("text");

                    b.Property<string>("DegreeObtained")
                        .HasColumnType("text");

                    b.Property<string>("EndYear")
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StartYear")
                        .HasColumnType("text");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("LocationId");

                    b.ToTable("UniversityAttendedModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.UniversityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UniversityModels");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.WorkingExperienceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantModelId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("text");

                    b.Property<string>("CompanyFrom")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CompanyPhone")
                        .HasColumnType("text");

                    b.Property<string>("CompanyPosition")
                        .HasColumnType("text");

                    b.Property<string>("CompanyTo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantModelId");

                    b.ToTable("WorkingExperienceModels");
                });

            modelBuilder.Entity("ApplicantPortal.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Admitted")
                        .HasColumnType("boolean");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Finalized")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ForeignApplicant")
                        .HasColumnType("boolean");

                    b.Property<bool?>("FormCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FormNo")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PictureUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("Pin")
                        .HasColumnType("text");

                    b.Property<bool?>("ResultUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("Sold")
                        .HasColumnType("boolean");

                    b.Property<string>("SoldBy")
                        .HasColumnType("text");

                    b.Property<bool?>("Started")
                        .HasColumnType("boolean");

                    b.Property<string>("Teller")
                        .HasColumnType("text");

                    b.Property<string>("TellerPhone")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("VoucherType")
                        .HasColumnType("integer");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicantModelProgrammeModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", null)
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantPortal.Domain.Entities.ProgrammeModel", null)
                        .WithMany()
                        .HasForeignKey("ProgrammesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.AcademicExperienceModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "ApplicantModel")
                        .WithMany()
                        .HasForeignKey("ApplicantModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantModel");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.AddressModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ApplicantIssueModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ApplicantModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.DistrictModel", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("ApplicantPortal.Domain.Entities.FormerSchoolModel", "FormerSchoolNew")
                        .WithMany()
                        .HasForeignKey("FormerSchoolNewId");

                    b.HasOne("ApplicantPortal.Domain.Entities.HallModel", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId");

                    b.HasOne("ApplicantPortal.Domain.Entities.CountryModel", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("ApplicantPortal.Domain.Entities.RegionModel", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("ApplicantPortal.Domain.Entities.ReligionModel", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.OwnsOne("ApplicantPortal.Domain.ValueObjects.ApplicantName", "ApplicantName", b1 =>
                        {
                            b1.Property<int>("ApplicantModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("Othernames")
                                .HasColumnType("text")
                                .HasColumnName("Othernames");

                            b1.HasKey("ApplicantModelId");

                            b1.ToTable("ApplicantModel");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantModelId");
                        });

                    b.OwnsOne("ApplicantPortal.Domain.ValueObjects.Money", "FeesPaid", b1 =>
                        {
                            b1.Property<int>("ApplicantModelId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("FeesPaid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FeesPaidCurrency");

                            b1.HasKey("ApplicantModelId");

                            b1.ToTable("ApplicantModel");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantModelId");
                        });

                    b.OwnsOne("ApplicantPortal.Domain.ValueObjects.Money", "HallFeesPaid", b1 =>
                        {
                            b1.Property<int>("ApplicantModelId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("HallFeesPaid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("HallFeesPaidCurrency");

                            b1.HasKey("ApplicantModelId");

                            b1.ToTable("ApplicantModel");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantModelId");
                        });

                    b.OwnsOne("ApplicantPortal.Domain.ValueObjects.ApplicantName", "PreviousName", b1 =>
                        {
                            b1.Property<int>("ApplicantModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PreviousFirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PreviousLastName");

                            b1.Property<string>("Othernames")
                                .HasColumnType("text")
                                .HasColumnName("PreviousOthernames");

                            b1.HasKey("ApplicantModelId");

                            b1.ToTable("ApplicantModel");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantModelId");
                        });

                    b.OwnsOne("ApplicantPortal.Domain.ValueObjects.IdCard", "IdCard", b1 =>
                        {
                            b1.Property<int>("ApplicantModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("NationalIDNo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("NationalIDNo");

                            b1.Property<string>("NationalIDType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("NationalIDType");

                            b1.HasKey("ApplicantModelId");

                            b1.ToTable("ApplicantModel");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantModelId");
                        });

                    b.Navigation("ApplicantName")
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("FeesPaid");

                    b.Navigation("FormerSchoolNew");

                    b.Navigation("Hall");

                    b.Navigation("HallFeesPaid");

                    b.Navigation("IdCard");

                    b.Navigation("Nationality");

                    b.Navigation("PreviousName");

                    b.Navigation("Region");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.Choices", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.HasOne("ApplicantPortal.Domain.Entities.ProgrammeModel", "FirstChoice")
                        .WithMany()
                        .HasForeignKey("FirstChoiceId");

                    b.HasOne("ApplicantPortal.Domain.Entities.ProgrammeModel", "SecondChoice")
                        .WithMany()
                        .HasForeignKey("SecondChoiceId");

                    b.HasOne("ApplicantPortal.Domain.Entities.ProgrammeModel", "ThirdChoice")
                        .WithMany()
                        .HasForeignKey("ThirdChoiceId");

                    b.Navigation("Applicant");

                    b.Navigation("FirstChoice");

                    b.Navigation("SecondChoice");

                    b.Navigation("ThirdChoice");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DepartmentModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.FacultyModel", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.DocumentUploadModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ProgrammeModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.RefereeModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "ApplicantModel")
                        .WithMany()
                        .HasForeignKey("ApplicantModelId");

                    b.Navigation("ApplicantModel");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ResearchModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ResearchPublicationModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.ResultUploadModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "ApplicantModel")
                        .WithMany()
                        .HasForeignKey("ApplicantModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantPortal.Domain.Entities.GradeModel", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantPortal.Domain.Entities.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantModel");

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SHSAttendedModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.HasOne("ApplicantPortal.Domain.Entities.RegionModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("ApplicantPortal.Domain.Entities.FormerSchoolModel", "Name")
                        .WithMany()
                        .HasForeignKey("NameId");

                    b.Navigation("Applicant");

                    b.Navigation("Location");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.SchoolModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.RegionModel", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.TodoList", b =>
                {
                    b.OwnsOne("ApplicantPortal.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<int>("TodoListId")
                                .HasColumnType("integer");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TodoListId");

                            b1.ToTable("TodoLists");

                            b1.WithOwner()
                                .HasForeignKey("TodoListId");
                        });

                    b.Navigation("Colour")
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.UniversityAttendedModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.HasOne("ApplicantPortal.Domain.Entities.CountryModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Applicant");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.WorkingExperienceModel", b =>
                {
                    b.HasOne("ApplicantPortal.Domain.Entities.ApplicantModel", "ApplicantModel")
                        .WithMany()
                        .HasForeignKey("ApplicantModelId");

                    b.Navigation("ApplicantModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicantPortal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicantPortal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantPortal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicantPortal.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicantPortal.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
